# Generated by Django 4.0.5 on 2022-06-25 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_touridea'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Comps name')),
                ('about', models.TextField(verbose_name='Comps about')),
                ('img', models.ImageField(upload_to='media', verbose_name='Comps image')),
            ],
            options={
                'verbose_name': 'Comps',
                'verbose_name_plural': 'Compses',
            },
        ),
    ]
